server:
  address: tcp://0.0.0.0:9091

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: two_factor
  rules: []

session:
  cookies:
    name: authelia_session
    domain: andreasmaita.com
    expiration: 3600
    inactivity: 300
    remember_me: 1M
    same_site: Lax

notifier:
  filesystem:
    filename: /config/notification.txt

storage:
  local:
    path: /config/db.sqlite3

identity_validation:
  reset_password:
    # JWT secret supplied via environment/file
