server:
  address: tcp://0.0.0.0:9091

log:
  level: info

theme: dark

totp:
  issuer: homelab
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2

access_control:
  default_policy: two_factor
  rules:
    - domain: "*.andreasmaita.com"
      resources:
        - "^/api/.*$"
        - "^/identity/.*$"
      policy: bypass
    - domain:
        - "jellyfin.andreasmaita.com"
        - "seerr.andreasmaita.com"
      policy: one_factor

session:
  name: authelia_session
  expiration: 1h
  inactivity: 10m
  cookies:
    - domain: andreasmaita.com
      authelia_url: https://auth.andreasmaita.com
  redis:
    host: authelia-redis
    port: 6379

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
