services:
  actual_server:
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ${DATA_ROOT}/app_data/actual-budget:/data
