services:
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    environment:
      - ND_USERNAME=${NAVIDROME_USER}
      - ND_PASSWORD_FILE=/run/secrets/navidrome-pass
    volumes:
      - ${DATA_ROOT}/music:/music
      - ${DATA_ROOT}/navidrome_db:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.${DOMAIN}`)"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
    networks:
      - proxy_net
      - backend

networks:
  proxy_net:
    external: true
  backend:
    internal: true

# secrets:
#   navidrome-pass:
#     file: ../../backups/secrets/navidrome-pass.secret
