services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN_FILE=/run/secrets/vaultwarden-admin-token
    volumes:
      - ${DATA_ROOT}/vaultwarden:/data
    networks:
      - backend
      - proxy_net

networks:
  proxy_net:
    external: true
  backend:
    internal: true
