# Based on https://github.com/JamesTurland/JimsGarage
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ~/homelab-config/data/app_data/nextcloud/appdata:/config
      - ~/homelab-config/data/app_data/nextcloud/data:/data
    ports:
      - 21000:80
      - 21001:443
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.nextcloud.entrypoints=http"
    #   - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.jimsgarage.co.uk`)"
    #   - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
    #   - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
    #   - "traefik.http.routers.nextcloud-secure.entrypoints=https"
    #   - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.jimsgarage.co.uk`)"
    #   - "traefik.http.routers.nextcloud-secure.tls=true"
    #   - "traefik.http.routers.nextcloud-secure.service=nextcloud"
    #   - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    #   - "traefik.docker.network=proxy"
    networks:
      proxy:

  # Own added for online office suite to work 
  collabora:
    image: collabora/code:latest
    container_name: collabora
    ports:
      - "9980:9980"
    restart: unless-stopped
    volumes:
      - /var/container/collabora/etc/coolwsd/:/etc/coolwsd/:rw
    environment:
      #- domain=example.com
      - username=${collaboraUser}
      - password=${collaboraPassword}
      - dictionaries=en_GB
      - TZ=Europe/London
    networks:
      proxy:
  
networks:
  proxy:
    external: true
