---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks/

# - Development:
#    - Github:
#       - abbr: GH
#         href: https://github.com/

# Add your own bookmark groups here
