---
# For configuration options and examples, see:
# https://gethomepage.dev/configs/bookmarks/

- Homelab:
    - Homelab Config (GitHub):
        - abbr: GH
          href: https://github.com/Andreas-PM/homelab-config
    - Cloudflare DNS:
        - abbr: DNS
          href: https://dash.cloudflare.com
    - Dockge Stack Manager:
        - abbr: DG
          href: http://100.106.40.5:20202
    - Tailscale Admin:
        - abbr: TS
          href: https://login.tailscale.com/admin

- Media APIs:
    - TMDB:
        - abbr: TM
          href: https://www.themoviedb.org/settings/api
    - Trakt Apps:
        - abbr: TR
          href: https://trakt.tv/oauth/applications
    - AniList Dev:
        - abbr: AL
          href: https://anilist.co/settings/developer
    - Steam API:
        - abbr: ST
          href: https://steamcommunity.com/dev/apikey
