services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - TZ=Europe/London
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=yamtrack
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    container_name: yamtrack-db
    environment:
      - POSTGRES_DB=yamtrack
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/homelab-config/data/app_data/yamtrack/db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - ~/homelab-config/data/app_data/yamtrack/redis_data:/data

volumes:
  redis_data:
