# Official Docker Compose template for Monica Personal CRM (Apache variant)
# Source: https://github.com/monicahq/docker
services:
  app:
    image: monica:latest
    depends_on:
      - db
    ports:
      # Default but used for many other services, so change to avoid conflicts
      # Change later to be docker network-specific and/or reverse proxied
      # - 8080:80
      - 24000:80
    environment:
      # Generate a key using: echo -n 'base64:'; openssl rand -base64 32
      - APP_KEY=${MONICA_APP_KEY}
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=${MONICA_DB_PASSWORD}
    volumes:
      - ~/homelab-config/data/app_data/monica/data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=${MONICA_DB_PASSWORD}
    volumes:
      - ~/homelab-config/data/app_data/monica/mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: monica_data
  mysql:
    name: monica_mysql
