services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      # Generate with `echo -n 'base64:'; openssl rand -base64 32`
      - APP_KEY=${MONICA_APP_KEY}
      - DB_HOST=db
      - DB_USERNAME=${MONICA_DB_USERNAME}
      - DB_PASSWORD=${MONICA_DB_PASSWORD}
    volumes:
      - ~/homelab-config/data/app_data/monica/data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=${MONICA_DB_USERNAME}
      - MYSQL_PASSWORD=${MONICA_DB_PASSWORD}
    volumes:
      - ~/homelab-config/data/app_data/monica/mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
