services:
  immich-server:
    networks:
      - homelab_net

  immich-machine-learning:
    networks:
      - homelab_net

  redis:
    networks:
      - homelab_net

  database:
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true
