services:
  joplin:
    image: joplin/server:latest
    restart: unless-stopped
    environment:
      - DB_PASSWORD_FILE=/run/secrets/joplin-db-pass
    volumes:
      - ${DATA_ROOT}/joplin:/data
    networks:
      - backend
      - proxy_net

  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN_FILE=/run/secrets/vaultwarden-admin-token
    volumes:
      - ${DATA_ROOT}/vaultwarden:/data
    networks:
      - backend
      - proxy_net

networks:
  proxy_net:
    external: true
  backend:
    internal: true

secrets:
  paperless-admin-pass:
    file: ../../backups/secrets/paperless-admin-pass.secret
  paperless-db-pass:
    file: ../../backups/secrets/paperless-db-pass.secret
  joplin-db-pass:
    file: ../../backups/secrets/joplin-db-pass.secret
  vaultwarden-admin-token:
    file: ../../backups/secrets/vaultwarden-admin-token.secret
