services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8085:8085 # qbittorrent
    volumes:
      - ~/homelab-config/data/app_data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - TZ=Europe/London
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=on
      - WIREGUARD_MTU=1280
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      # Automatically updates qBittorrent when ProtonVPN changes the port
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -qO- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://localhost:8085/api/v2/app/setPreferences'
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8085
    volumes:
      - ~/homelab-config/data/app_data/qbittorrent:/config
      - ~/homelab-config/data/media/downloads:/downloads
      - ~/homelab-config/data/media/audiobooks:/audiobooks
      - ~/homelab-config/data/media/books:/books
      - ~/homelab-config/data/media/movies:/movies
      - ~/homelab-config/data/media/music:/music
      - ~/homelab-config/data/media/podcasts:/podcasts
      - ~/homelab-config/data/media/tv:/tv
    depends_on:
      - gluetun
    restart: always
