services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DATA_DIR}/app_data/lidarr/data:/config
      - ${DATA_DIR}/media/music:/music #optional
      - ${DATA_DIR}/media/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
