#!/usr/bin/env python3
"""
Analyze .env for duplicate keys, duplicate values, deprecated vars,
and produce a masked report plus a `.env.optimized.example` (dry-run).

Writes:
 - backups/env-analysis-report.txt
 - .env.optimized.example

Usage: python3 scripts/analyze_env.py
"""

import os
import re
import hashlib
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ENV_PATH = os.path.join(ROOT, ".env")
REPORT_DIR = os.path.join(ROOT, "backups")
REPORT_PATH = os.path.join(REPORT_DIR, "env-analysis-report.txt")
OUT_EXAMPLE = os.path.join(ROOT, ".env.optimized.example")


def read_env(path):
    entries = []
    if not os.path.exists(path):
        return entries
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            raw = line.rstrip("\n")
            s = raw.strip()
            if not s or s.startswith("#"):
                continue
            m = re.match(r"^([A-Za-z0-9_\-\.]+)\s*=\s*(.*)$", raw)
            if not m:
                continue
            key = m.group(1)
            val = m.group(2).strip()
            if (val.startswith("'") and val.endswith("'")) or (
                val.startswith('"') and val.endswith('"')
            ):
                val = val[1:-1]
            entries.append((key, val, i))
    return entries


def is_secret_key(key):
    u = key.upper()
    secrets_words = [
        "PASS",
        "PASSWORD",
        "SECRET",
        "TOKEN",
        "KEY",
        "JWT",
        "API",
        "S3",
        "ENCRYPT",
        "PRIVATE",
    ]
    return any(w in u for w in secrets_words)


def is_url(v):
    return v.startswith("http://") or v.startswith("https://")


def is_path(v):
    return v.startswith("/") or v.startswith("~")


def short_hash(v):
    return hashlib.sha256(v.encode("utf-8")).hexdigest()[:12]


def analyze(entries):
    report = []
    report.append(f"Analyzed .env: {len(entries)} variables")

    key_map = defaultdict(list)
    val_map = defaultdict(list)
    for key, val, lineno in entries:
        key_map[key].append((val, lineno))
        val_map[val].append(key)

    # duplicate keys
    dups_keys = {k: v for k, v in key_map.items() if len(v) > 1}
    if dups_keys:
        report.append("\nDuplicate keys found:")
        for k, vs in dups_keys.items():
            lines = ", ".join(str(l) for _, l in vs)
            report.append(f" - {k} at lines {lines}")
    else:
        report.append("\nNo duplicate keys found.")

    # duplicate values (potential reused secrets)
    reused = {v: ks for v, ks in val_map.items() if v and len(ks) > 1}
    if reused:
        report.append("\nReused values detected (masked):")
        for v, ks in reused.items():
            h = short_hash(v)
            report.append(f" - sha256:{h} used by: {', '.join(ks)} (count={len(ks)})")
    else:
        report.append("\nNo reused values detected.")

    # secrets heuristic
    secret_keys = []
    for key, val, _ in entries:
        if is_secret_key(key) or (
            len(val) >= 16
            and not is_url(val)
            and not is_path(val)
            and not val.isdigit()
        ):
            secret_keys.append(key)
    report.append(f"\nSecret-like keys detected: {len(secret_keys)}")
    if secret_keys:
        report.append(" - " + ", ".join(secret_keys))

    # deprecated patterns
    deprecated = []
    for key in key_map:
        if (
            key.startswith("RESTC_")
            or key.startswith("REST_")
            and not key.startswith("RESTIC_")
        ):
            deprecated.append(key)
    if deprecated:
        report.append("\nDeprecated-style keys detected:")
        for k in deprecated:
            report.append(f" - {k} (consider migrating to RESTIC_*)")

    # quick stats
    ports = [
        k for k, _, _ in entries if k.upper().endswith("_PORT") or "PORT" in k.upper()
    ]
    report.append(f"\nPort-like keys: {len(ports)}")

    # recommendations
    report.append("\nRecommendations:")
    report.append(
        " - Rotate any exposed API tokens and secrets (CF_TOKEN, TUNNEL_TOKEN, RESTIC keys)."
    )
    if reused:
        report.append(
            " - Replace reused passwords with unique per-service secrets; avoid password reuse."
        )
    report.append(
        " - Migrate secrets to a secrets manager (Infisical or Docker secrets)."
    )
    report.append(" - Remove deprecated RESTC_/REST_ keys; standardize on RESTIC_.")
    report.append(
        " - Use ./scripts/generate-secrets.sh to create fresh secrets where possible."
    )

    return "\n".join(report), reused, secret_keys, deprecated


def generate_example(entries, reused_vals, secret_keys, deprecated):
    lines = []
    lines.append("# Optimized .env example (generated by scripts/analyze_env.py)")
    lines.append(
        "# NOTE: Secrets are left blank here. Fill them or run ./scripts/generate-secrets.sh"
    )
    lines.append("")

    seen = set()
    for key, val, _ in entries:
        if key in seen:
            continue
        seen.add(key)
        comment = ""
        ukey = key.upper()
        if key in deprecated:
            comment = " # DEPRECATED - consider migrating"

        if is_secret_key(key) or key in secret_keys:
            lines.append(f"{key}={comment}")
        elif key.endswith("_PORT") or "PORT" in ukey or val.isdigit():
            # keep example port values
            lines.append(f"{key}={val}{comment}")
        elif is_url(val):
            lines.append(f"{key}={val}{comment}")
        elif is_path(val):
            # generic path
            if "DATA_ROOT" in ukey or "UPLOAD" in ukey or "LOCATION" in ukey:
                lines.append(f"{key}=/home/youruser/homelab-data{comment}")
            else:
                lines.append(f"{key}=/path/to/{key.lower()}{comment}")
        else:
            # mask potentially sensitive short tokens
            if len(val) >= 8 and not val.isdigit():
                lines.append(f"{key}={comment}")
            else:
                lines.append(f"{key}={val}{comment}")

    lines.append("")
    lines.append("# End of optimized example")
    return "\n".join(lines)


def write_report(report_text):
    os.makedirs(REPORT_DIR, exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report_text)


def write_example(text):
    with open(OUT_EXAMPLE, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    entries = read_env(ENV_PATH)
    report_text, reused, secret_keys, deprecated = analyze(entries)
    write_report(report_text)
    example = generate_example(entries, reused, secret_keys, deprecated)
    write_example(example)
    print("Wrote report to:", REPORT_PATH)
    print("Wrote optimized example to:", OUT_EXAMPLE)


if __name__ == "__main__":
    main()
