# Based on https://www.navidrome.org/docs/installation/docker/

services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # must own the data folder and be able to read music folder(s). See Permissions below
    ports:
      - "4533:4533"
    restart: unless-stopped
    # environment:
    # Optional: put your config options customization here. Examples:
    # ND_LOGLEVEL: debug
    volumes:
      - ${DATA_DIR}/app_data/navidrome:/data
      - ${DATA_DIR}/media/music:/music:ro
