# Couldn't find official so sourced it after https://github.com/JamesTurland/JimsGarage/blob/main/Cloudflare-HTTPS/cloudflared/docker-compose.yaml

services:
  tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # secrets:
    #   - cloudflare_tunnel_token
    restart: unless-stopped
    networks:
      - proxy

# secrets:
# cloudflare_tunnel_token:
#   file: service-secrets/cloudflare-tunnel-token.txt

networks:
  proxy:
    external: true
