name: productivity

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:9
    container_name: forgejo
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - FORGEJO__database__DB_TYPE=sqlite3
    volumes:
      - ${HOME}/homelab-data/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${FORGEJO_WEB_PORT}:3000"
      - "${FORGEJO_SSH_PORT}:22"
    restart: unless-stopped
    networks:
      - homelab_net

  dufs:
    image: sigoden/dufs:latest
    container_name: dufs
    # Command sets path and allows All permissions (-A)
    command: /data -A
    volumes:
      - ${HOME}/homelab-data/dufs:/data
    ports:
      - "${WEBDAV_PORT}:5000"
    restart: unless-stopped
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true
