name: productivity

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__repository__ENABLE_PUSH_CREATE_USER=true
      - FORGEJO__server__ROOT_URL=${FORGEJO__server__ROOT_URL}
      - FORGEJO__server__HTTP_ADDR=${FORGEJO__server__HTTP_ADDR}
      - FORGEJO__server__HTTP_PORT=${FORGEJO__server__HTTP_PORT}
      - FORGEJO__server__SSH_DOMAIN=${FORGEJO__server__SSH_DOMAIN}
      - FORGEJO__server__OFFLINE_MODE=${FORGEJO__server__OFFLINE_MODE}
    volumes:
      - ../homelab-data/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${FORGEJO_WEB_PORT}:3000"
      - "${FORGEJO_SSH_PORT}:22"
    restart: unless-stopped
    networks:
      - homelab_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M

  dufs:
    image: sigoden/dufs:latest
    container_name: dufs
    command: /data -A -a ${DUFS_auth}@/:rw
    volumes:
      - ../homelab-data/dufs:/data
    ports:
      - "${DUFS_PORT}:5000"
    restart: unless-stopped
    networks:
      - homelab_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

networks:
  homelab_net:
    external: true
