services:
  mailserver:
    image: docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    restart: unless-stopped
    env_file:
      - ../../backups/secrets/mailserver.env
    hostname: mail
    domainname: ${MAIL_DOMAIN:-andreasmaita.com}
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ../../data/mailserver/maildata:/var/mail
      - ../../data/mailserver/state:/var/mail-state
      - ../../backups/secrets/mailserver:/tmp/docker-mailserver
      - ../../backups/secrets/mail/dkim:/tmp/docker-mailserver/dkim
    networks:
      - infrastructure_internal
    healthcheck:
      test: ["CMD-SHELL", "sleep 1 && exit 0"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  infrastructure_internal:
    external: true
