services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/qbit:/config
      - ${DATA_ROOT}/downloads:/downloads
    ports:
      - "${QBITTORRENT_WEBUI_PORT}:8080"
    networks:
      - proxy_net
      - backend
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.qbittorrent.rule=Host(`qbit.${DOMAIN}`)"
    #   - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    
  prowlarr:
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/prowlarr:/config
    networks:
      - backend
      - proxy_net

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/radarr:/config
    networks:
      - backend
      - proxy_net

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT}/sonarr:/config
    networks:
      - backend
      - proxy_net

networks:
  proxy_net:
    external: true
  backend:
    internal: true
